apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microservice
    version: v1.0
  name: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
      version: v1.0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microservice
        version: v1.0
    spec:
      containers:
      - image: microservice:v1.0
        name: microservice
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: microservice
  name: microservice
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: microservice
  type: ClusterIP
status:
  loadBalancer: {}
