apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: goods
  name: goods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goods
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: goods
    spec:
      containers:
      - image: goods:v1.0
        name: goods
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: goods
  name: goods
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: goods
  type: ClusterIP
status:
  loadBalancer: {}
